### ISSUE TITLE
allow non-official clubs

### ISSUE THREAD

**Issue by axd1967** [slashme/goclubdb#31]
as an informal club organiser, I would like to be able to specify my club that meets weekly, but is not affiliated with an association, so that I can draw attention to the club.

Is it OK if I create a layer such as `BE-informal` or `BE-unlisted` (as it happens to be in Belgium)? or maybe a layer `XX-informal`?

**Comment by slashme** [comment]
Thanks for this question - I think there are a number of options:

* Create your club and don't worry: after all, this isn't the list of clubs that's maintained by the Belgian Go Federation, so maybe just mention in the club description or the contact field that it isn't an official club of the Federation. This would be the least intrusive solution.  
* Create a layer for non-aligned clubs worldwide: surely there will be a number of cases where there are clubs which are explicitly not affiliated to their national organisations. The downside of this is that these clubs won't cluster with their neighbours when the map is zoomed out.  
* Create a new type of club with its own marker type. This would be reasonably straightforward to implement, but I'm not sure that there's enough demand to make this worthwhile, and it wouldn't solve the problem faced by clubs that are explicitly not affiliated to their national organisation (e.g. for political reasons).

Please let me know what you think!

**Comment by axd1967** [comment]
option 1 seems the most interesting for now...

http://senseis.xmp.net/?PlacesWithoutAClub indicates that maybe there is a use case for "club-less meeting occasions" - maybe a separate layer for _players_ that are looking for clubs.

**Comment by slashme** [comment]
That's a perfectly reasonable idea. Feel free to make such a layer on the database if you like, and if it attracts players, I'll make it visible on the map.
